# Generated by Django 5.1 on 2024-09-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receipt_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='new_field',
        ),
    ]
