# Generated by Django 5.1 on 2024-08-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receipt_deadline_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='deadline_notice',
            new_name='test',
        ),
    ]
