# Generated by Django 5.1 on 2024-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_receipt_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
