# Generated by Django 5.1 on 2024-09-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_test_receipt_deadline_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='state',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('done', 'Done')], default=None, max_length=20, null=True),
        ),
    ]
