# Generated by Django 5.1 on 2024-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_receipt_order_date_alter_receipt_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(blank=True, through='api.OrderInfo', to='api.product'),
        ),
    ]
