# Generated by Django 5.1 on 2024-10-07 09:03

import api.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_new_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='state_new',
            field=django_choices_field.fields.TextChoicesField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('done', 'Done')], choices_enum=api.models.StatusChoices, default='active', max_length=9),
        ),
    ]
