# Generated by Django 5.1 on 2024-10-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_receipt_state_new_alter_receipt_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='number',
            new_name='customer_number',
        ),
    ]
