# Generated by Django 5.1 on 2024-10-07 09:14

import api.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('g', 'Good'), ('s', 'Service')], choices_enum=api.models.ProductTypeChoices, max_length=1),
        ),
    ]
