# Generated by Django 5.1 on 2024-10-07 09:14

import api.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='state',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('done', 'Done')], choices_enum=api.models.StatusChoices, max_length=9),
        ),
    ]
