# Generated by Django 5.1 on 2024-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_test_receipt_deadline_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
