# Generated by Django 5.1 on 2024-08-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_deadline_notice_receipt_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='test',
            new_name='deadline_notice',
        ),
    ]
